version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: mongodb-docker
    network_mode: host
    restart: always

  api-gateway:
    build: ./api-gateway/
    restart: always
    container_name: api-gateway-docker
    network_mode: host
    ports:
      - 8082:8082
    depends_on:
     - track

  config-service:
    build: ./config-server/
    restart: always
    network_mode: host
    container_name: config-docker
    ports:
      - 8601:8601

  eureka-service:
    build: ./eureka-server/
    restart: always
    network_mode: host
    container_name: eureka-docker
    ports:
      - 8680:8680

  track-service:
    build: ./track-service/
    restart: always
    network_mode: host
    container_name: track-docker
    ports:
      - 8090:8090
    depends_on:
      - config
      - mongo
      - eureka


  user-service:
    build: ./user-services/
    restart: always
    network_mode: host
    container_name: user-docker
    ports:
      - 8080:8080



