version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: mongodb-docker
    network_mode: host
    restart: always

  api-gateway:
    build: ./api-gateway-pattern/
    restart: always
    container_name: api-gateway-docker
    network_mode: host
    depends_on:
      - track
    ports:
      - 8081:8081

  config:
    build: ./config-server/
    restart: always
    network_mode: host
    container_name: config-docker
    ports:
      - 8600:8600

  eureka:
    build: ./eureka-server/
    restart: always
    network_mode: host
    container_name: eureka-docker
    ports:
      - 7770:7770

  track:
    build: ./track-service/
    restart: always
    network_mode: host
    container_name: track-docker
    ports:
      - 8090:8090
    depends_on:
      - config
      - mongo
      - eureka

  user:
    build: ./user-service/
    restart: always
    network_mode: host
    container_name: user-docker
    ports:
      - 8080:8080



